### PR TITLE
clean NBA_Model_GUI.py

### PR DESCRIPTION
**Pull request by vikramraju5**

### CODE REVIEW

**Comment by km2018** [comment]
Link to #5

**Comment by km2018** [comment]
On line 13, perhaps extract those dimensions into constants. I'm not sure what each of the 4 numbers mean in setGeometry.

**Comment by km2018** [comment]
For functions where you pass in a string, extract those strings into constant members of the class. While some of them are somewhat self-explanatory in terms of their function, I think that it's good practice and allows the code to be more organized. Having all of the constants in one place is more readable and makes the code more robust. <br />

Examples of this: lines 20, 26, and 29

**Comment by km2018** [comment]
Extract numbers in line 41 - (btn.move(0, 100)) into constants. I am not sure what these numbers mean. This is another example of "magic numbers".

**Comment by ericlian1** [comment]
I wrote this gui file as a super basic vanilla GUI so all the buttons and layout would change.  I don't think there's much need to extract magic numbers here since there aren't any (they're all subject to change).

**Pull request merged**
